[Variables]
;menu bar
BackgroundHeight = 25
PaddingLeft = 10
PaddingRight = 10
PaddingTop = 1
PaddingBottom = 1
;colors
BackgroundColor = 51,51,51,255
BarColor = 30,30,30,255
LowerBarColor = 71,71,71,255
;power
PowerColor = 255,255,255,255
ShutdownColor = 54,135,160,255
HoveredShutdownColor = 66,212,244,255
ConfirmSizeBox = 166.66666666667
ShutdownBackgroundColor = 0,0,0,210
SquareSize = (#SCREENAREAHEIGHT#/4.5)